name: Ticket app CI

on: push

permissions:
        contents: read

jobs:
    runner-check:
        runs-on: ubuntu-24.04
        steps:
            - name: Check out code
              uses: actions/checkout@v7

            - name: Set up Pythion
              uses: actions/setup-python@v7
              with:
                    python-version: "3.12"

            - name:  Shoe Python version
              run: python --version